<?php

namespace AppBundle\Repository;

/**
 * categorisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categorisationRepository extends \Doctrine\ORM\EntityRepository
{
}
