<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Category;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllNames()
    {
        return array_map(
            function (Category $category) {
                return $category->getName();
            },
            $this->findBy([], ['name' => 'ASC'])
        );
    }
}
