<?php

namespace AppBundle\Repository;

/**
 * TodoCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TodoCategoryRepository extends \Doctrine\ORM\EntityRepository
{

}
